# Generated by Django 4.1.2 on 2022-10-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lyrics',
            name='song_id',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
